name: Demo
on: [push]
jobs:
  demo:
    runs-on: windows-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Build Bug
        run: cl demo.cpp
      - name: Showcase Bug
        run: |
          type demo.cpp
          demo.exe
      - name: Showcase Fix
        run: |
          cl demo.cpp /permissive-
          demo.exe
